b2s_user = 'BHOSTRTPP'
b2s_pass = 'pstreport6'
ofm_user = 'OHOSTRTPP'
ofm_pass = 'pstreport6'
ssp_user = 'SHOPSTTPP'
ssp_pass = 'pstreport6'
ssp_user2 = 'SHOPSTVPK'
ssp_pass2 = 'pstpst4321'
pwb_url = 'http://10.5.204.32/BUYERREPORT/login.aspx'
pwb_user = 'HOPSTTPP'
pwb_pass = 'report2'
chg_url = 'http://hwmmsweb/buyerreport/login.aspx'
chg_user = 'HHOOPMKJ'
chg_pass = 'chg12345'
sspwds_server = 'SPHQWHMDB02'
sspwds_user = 'PRTHANAP'
sspwds_pass = 'report06'
b2s_master = 'MMB2SUSR/INV551P1(BHOSTRTPP)'
b2s_master_bar = 'MMB2SLIB/CYPRC(BHOSTRTPP)'


